NF: add an IDE help
rust-embedded/discovery pull request #481
Opened 2022-11-12 14:03 UTC by Arthur-Milchior

I had some troubles using IntelliJ to work with the code examples.  I thus added a page that tries to help the user getting the best out of their IDE with this book.

Some of the solution are not IntelliJ specific, so I separated this page into a general purpose help and a section that concern specific IDE.

Since I only use IntelliJ, I can't provide section for Code, for examples. So, I invited users of other IDE to contribute.

Ideally, I'd love for someone to get how to use the debugger with the IDE too. However, even if this page is not perfect, I believe it may still be an improvement for the next reader

2022-11-12 14:03 UTC, rust-highfive commented
r? @andre-richter

(rust-highfive has picked a reviewer for you, use r? to override)

2022-11-14 09:26 UTC, eldruin reviewed
Thanks for the suggestion.
Here some improvements / corrections.

@hargoniX could you also check on this? especially the part about removing dependencies/features

2022-11-14 09:26 UTC, eldruin commented on microbit/src/03-setup/IDE.md
> +# Getting the best of your IDE
```suggestion
# Getting the most out of your IDE
```

2022-11-14 09:26 UTC, eldruin commented on microbit/src/03-setup/IDE.md
> +All codes in this book works assume that you use a simple terminal to build your code
```suggestion
All code in this book assumes that you use a simple terminal to build your code,
```

2022-11-14 09:26 UTC, eldruin commented on microbit/src/03-setup/IDE.md
> +your preferred shortcuts and much more. This section explains how to get the best
```suggestion
your preferred shortcuts and much more. This section explains how to get the most out
```

2022-11-14 09:26 UTC, eldruin commented on microbit/src/03-setup/IDE.md
> +Some IDEs fail to understand the code, because it fails to determine whether a term
```suggestion
Some IDEs fail to understand the code, because they fail to determine whether a term
```

2022-11-14 09:26 UTC, eldruin commented on microbit/src/03-setup/IDE.md
> +is defined in microbit or microbit-v2 codebase. If you fail to get auto-completion to work,
```suggestion
is defined in the microbit or microbit-v2 codebase. If you fail to get auto-completion to work,
```

2022-11-14 09:26 UTC, eldruin commented on microbit/src/03-setup/IDE.md
> +* in code, you must remove the part of the code guarded by `#[cfg(feature = "vI")]`, and the guard
```suggestion
 in the `Cargo.toml` file you must remove the dependency and features you do not use (the part guarded by `#[cfg(feature = "vI")]` and the guard itself)
```

2022-11-14 09:26 UTC, eldruin commented on microbit/src/03-setup/IDE.md
> +# IDEs configuration
```suggestion
# IDE configuration
```

2022-11-14 09:26 UTC, eldruin commented on microbit/src/03-setup/IDE.md
> +Below, we explain how to configure your IDE to get the best out of this book.
```suggestion
Below, we explain how to configure your IDE to get the most out of this book.
```

2022-11-14 09:26 UTC, eldruin commented on microbit/src/03-setup/IDE.md
> +reader get the best experience out of it.
```suggestion
reader can get the best experience out of it.
```

2022-11-14 09:26 UTC, eldruin commented on microbit/src/03-setup/IDE.md
> +When editing IntelliJ build configuration, here are a few non-default values:
```suggestion
When editing the IntelliJ build configuration, here are a few non-default values:
```

2022-11-14 09:26 UTC, eldruin commented on microbit/src/03-setup/IDE.md
> +* You should check "Emulate terminal in output console". Otherwise, your program will fail to print text to a terminal
```suggestion
* You should enable "Emulate terminal in output console". Otherwise, your program will fail to print text to a terminal
```

2022-11-14 09:26 UTC, eldruin commented on microbit/src/03-setup/IDE.md
> +* you should edit the command. When this book tells you to run `cargo embed FLAGS`,
```suggestion
* You should edit the command. When this book tells you to run `cargo embed FLAGS`,
```

2022-11-14 09:26 UTC, eldruin commented on microbit/src/03-setup/IDE.md
> +you'll need to replace the default value `run` by the command `embed FLAGS`,
```suggestion
You'll need to replace the default value `run` by the command `embed FLAGS`,
```

2022-11-14 09:26 UTC, eldruin commented on microbit/src/03-setup/IDE.md
> +* You should ensure that the working directory is `microbit/src/N-name`, with `N-name` the directory of the chapter you
```suggestion
* You should ensure that the working directory is `microbit/src/N-name`, with `N-name` being the directory of the chapter you
```

2024-04-30 17:18 UTC, BartMassey requested changes
There's some grammar that needs a bit of cleaning up here: can provide specifics on request.

After that, this should be merged.

2024-05-01 13:24 UTC, eldruin commented
@BartMassey a more in-depth review would indeed be welcome.

2024-05-01 16:03 UTC, BartMassey approved these changes
I had missed this commit. Looks great now.

2024-05-02 06:19 UTC, eldruin approved these changes
Thank you!

2024-05-02 06:26 UTC, merged