Updating Chapter 8 with more inclusive terms
rust-embedded/discovery pull request #486
Opened 2022-11-25 16:36 UTC by rmhyman

The terms master/slave should not be propagated for future technologists to absorb. Made changes to text and images (some resizing may be necessary). I'm not sure this terminology is being used in subsequent chapters, but I'm more than happy to update them as I encounter them.

2022-11-25 16:36 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @andre-richter (or someone else) soon.

Please see [the contribution instructions](https://rustc-dev-guide.rust-lang.org/contributing.html) for more information.

2022-11-26 17:52 UTC, adamgreig requested changes
Thanks! These are also the official terms for I2C now; the spec was updated last year.

I noticed one typo, and also I think it would be better if we could use the SVG version of the new images from Wikipedia - could you try changing to those please?

2022-11-26 17:52 UTC, adamgreig commented on microbit/src/08-i2c/README.md
> +drives the communication with a target device. Several devices, both conntrollers and targets, can be
```suggestion
drives the communication with a target device. Several devices, both controllers and targets, can be
```

2022-11-26 21:22 UTC, rmhyman commented
> Thanks! These are also the official terms for I2C now; the spec was updated last year.
> 
> I noticed one typo, and also I think it would be better if we could use the SVG version of the new images from Wikipedia - could you try changing to those please?

That's good to know that the spec was updated 😃 . I've fixed the typo and updated the images to use the SVG file instead of the PNG version.

2022-11-27 23:21 UTC, adamgreig approved these changes
Thanks!

bors r+

2022-11-27 23:29 UTC, merged